### PR TITLE
Adding Rane SL1 support 

### PR DESCRIPTION
**Pull request by redsand**
Note, the SAMPLERATE needs to be set to 44100 to work (in pideck)

Additionally, additional LOAD buttons are missing.  I'm currently in the works of adding this support. stand by for another pull request shortly

### CODE REVIEW

**Comment by redsand** [comment]
Adds plug-in ready support for the Rane SL-1 and adds additional LOAD and CUE buttons to manage the second deck/interface

**Comment by redsand** [comment]
Video... 
https://m.youtube.com/watch?feature=youtu.be&v=9Wvb70eOkyE

**Comment by redsand** [comment]
Adds page down/up support on right side for track navigation, adds combo timecode toggle for all decks, additionally Auto Cues to beginning of song on load. (this allwos me to use absolute offsets and jump to portions of a song I want to cue it up on the fly. before, this required two button clicks, and was always a requirement.  Finally, adds phono software pre-amp support (seems to work just fine for my taste)

**Comment by korotkov13** [comment]
Good job! It works with my sl-1 great.

**Comment by korotkov13** [comment]
@redsand I was little hurried about saying that everything works, because I have audio glitches with pitch band, while track is playing, like it's not constant rpm. and while loading track to another deck, it glitches. Do you have the same issues?

**Comment by danielhjames** [comment]
Thanks @redsand !

**Pull request merged**
